// Code generated by protoc-gen-go. DO NOT EDIT.
// source: annotations.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SQLIndex struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields               string   `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SQLIndex) Reset()         { *m = SQLIndex{} }
func (m *SQLIndex) String() string { return proto.CompactTextString(m) }
func (*SQLIndex) ProtoMessage()    {}
func (*SQLIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_75c6b13947912f81, []int{0}
}
func (m *SQLIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SQLIndex.Unmarshal(m, b)
}
func (m *SQLIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SQLIndex.Marshal(b, m, deterministic)
}
func (dst *SQLIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQLIndex.Merge(dst, src)
}
func (m *SQLIndex) XXX_Size() int {
	return xxx_messageInfo_SQLIndex.Size(m)
}
func (m *SQLIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_SQLIndex.DiscardUnknown(m)
}

var xxx_messageInfo_SQLIndex proto.InternalMessageInfo

func (m *SQLIndex) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SQLIndex) GetFields() string {
	if m != nil {
		return m.Fields
	}
	return ""
}

func (m *SQLIndex) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SQLAssociation struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Pk                   string   `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	Fk                   string   `protobuf:"bytes,3,opt,name=fk,proto3" json:"fk,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SQLAssociation) Reset()         { *m = SQLAssociation{} }
func (m *SQLAssociation) String() string { return proto.CompactTextString(m) }
func (*SQLAssociation) ProtoMessage()    {}
func (*SQLAssociation) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_75c6b13947912f81, []int{1}
}
func (m *SQLAssociation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SQLAssociation.Unmarshal(m, b)
}
func (m *SQLAssociation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SQLAssociation.Marshal(b, m, deterministic)
}
func (dst *SQLAssociation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQLAssociation.Merge(dst, src)
}
func (m *SQLAssociation) XXX_Size() int {
	return xxx_messageInfo_SQLAssociation.Size(m)
}
func (m *SQLAssociation) XXX_DiscardUnknown() {
	xxx_messageInfo_SQLAssociation.DiscardUnknown(m)
}

var xxx_messageInfo_SQLAssociation proto.InternalMessageInfo

func (m *SQLAssociation) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *SQLAssociation) GetPk() string {
	if m != nil {
		return m.Pk
	}
	return ""
}

func (m *SQLAssociation) GetFk() string {
	if m != nil {
		return m.Fk
	}
	return ""
}

func (m *SQLAssociation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SQLFieldOptions struct {
	Unique               bool     `protobuf:"varint,1,opt,name=unique,proto3" json:"unique,omitempty"`
	Index                bool     `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Indextype            string   `protobuf:"bytes,3,opt,name=indextype,proto3" json:"indextype,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Primarykey           bool     `protobuf:"varint,5,opt,name=primarykey,proto3" json:"primarykey,omitempty"`
	Notnull              bool     `protobuf:"varint,6,opt,name=notnull,proto3" json:"notnull,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Default              string   `protobuf:"bytes,8,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SQLFieldOptions) Reset()         { *m = SQLFieldOptions{} }
func (m *SQLFieldOptions) String() string { return proto.CompactTextString(m) }
func (*SQLFieldOptions) ProtoMessage()    {}
func (*SQLFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_75c6b13947912f81, []int{2}
}
func (m *SQLFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SQLFieldOptions.Unmarshal(m, b)
}
func (m *SQLFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SQLFieldOptions.Marshal(b, m, deterministic)
}
func (dst *SQLFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQLFieldOptions.Merge(dst, src)
}
func (m *SQLFieldOptions) XXX_Size() int {
	return xxx_messageInfo_SQLFieldOptions.Size(m)
}
func (m *SQLFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SQLFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SQLFieldOptions proto.InternalMessageInfo

func (m *SQLFieldOptions) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *SQLFieldOptions) GetIndex() bool {
	if m != nil {
		return m.Index
	}
	return false
}

func (m *SQLFieldOptions) GetIndextype() string {
	if m != nil {
		return m.Indextype
	}
	return ""
}

func (m *SQLFieldOptions) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SQLFieldOptions) GetPrimarykey() bool {
	if m != nil {
		return m.Primarykey
	}
	return false
}

func (m *SQLFieldOptions) GetNotnull() bool {
	if m != nil {
		return m.Notnull
	}
	return false
}

func (m *SQLFieldOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SQLFieldOptions) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

type GraphQLType struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Generate             bool     `protobuf:"varint,3,opt,name=generate,proto3" json:"generate,omitempty"`
	Definition           string   `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphQLType) Reset()         { *m = GraphQLType{} }
func (m *GraphQLType) String() string { return proto.CompactTextString(m) }
func (*GraphQLType) ProtoMessage()    {}
func (*GraphQLType) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_75c6b13947912f81, []int{3}
}
func (m *GraphQLType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQLType.Unmarshal(m, b)
}
func (m *GraphQLType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQLType.Marshal(b, m, deterministic)
}
func (dst *GraphQLType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQLType.Merge(dst, src)
}
func (m *GraphQLType) XXX_Size() int {
	return xxx_messageInfo_GraphQLType.Size(m)
}
func (m *GraphQLType) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQLType.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQLType proto.InternalMessageInfo

func (m *GraphQLType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphQLType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GraphQLType) GetGenerate() bool {
	if m != nil {
		return m.Generate
	}
	return false
}

func (m *GraphQLType) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type GraphQLUnion struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Tables               string   `protobuf:"bytes,4,opt,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphQLUnion) Reset()         { *m = GraphQLUnion{} }
func (m *GraphQLUnion) String() string { return proto.CompactTextString(m) }
func (*GraphQLUnion) ProtoMessage()    {}
func (*GraphQLUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_75c6b13947912f81, []int{4}
}
func (m *GraphQLUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQLUnion.Unmarshal(m, b)
}
func (m *GraphQLUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQLUnion.Marshal(b, m, deterministic)
}
func (dst *GraphQLUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQLUnion.Merge(dst, src)
}
func (m *GraphQLUnion) XXX_Size() int {
	return xxx_messageInfo_GraphQLUnion.Size(m)
}
func (m *GraphQLUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQLUnion.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQLUnion proto.InternalMessageInfo

func (m *GraphQLUnion) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphQLUnion) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GraphQLUnion) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GraphQLUnion) GetTables() string {
	if m != nil {
		return m.Tables
	}
	return ""
}

type SQLMessageOptions struct {
	Index                *SQLIndex       `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Index2               *SQLIndex       `protobuf:"bytes,2,opt,name=index2,proto3" json:"index2,omitempty"`
	Index3               *SQLIndex       `protobuf:"bytes,3,opt,name=index3,proto3" json:"index3,omitempty"`
	Index4               *SQLIndex       `protobuf:"bytes,4,opt,name=index4,proto3" json:"index4,omitempty"`
	Index5               *SQLIndex       `protobuf:"bytes,5,opt,name=index5,proto3" json:"index5,omitempty"`
	Index6               *SQLIndex       `protobuf:"bytes,6,opt,name=index6,proto3" json:"index6,omitempty"`
	Index7               *SQLIndex       `protobuf:"bytes,7,opt,name=index7,proto3" json:"index7,omitempty"`
	Index8               *SQLIndex       `protobuf:"bytes,8,opt,name=index8,proto3" json:"index8,omitempty"`
	Index9               *SQLIndex       `protobuf:"bytes,9,opt,name=index9,proto3" json:"index9,omitempty"`
	Index10              *SQLIndex       `protobuf:"bytes,10,opt,name=index10,proto3" json:"index10,omitempty"`
	Index11              *SQLIndex       `protobuf:"bytes,11,opt,name=index11,proto3" json:"index11,omitempty"`
	Index12              *SQLIndex       `protobuf:"bytes,12,opt,name=index12,proto3" json:"index12,omitempty"`
	Index13              *SQLIndex       `protobuf:"bytes,13,opt,name=index13,proto3" json:"index13,omitempty"`
	Index14              *SQLIndex       `protobuf:"bytes,14,opt,name=index14,proto3" json:"index14,omitempty"`
	Index15              *SQLIndex       `protobuf:"bytes,15,opt,name=index15,proto3" json:"index15,omitempty"`
	Index16              *SQLIndex       `protobuf:"bytes,16,opt,name=index16,proto3" json:"index16,omitempty"`
	Index17              *SQLIndex       `protobuf:"bytes,17,opt,name=index17,proto3" json:"index17,omitempty"`
	Index18              *SQLIndex       `protobuf:"bytes,18,opt,name=index18,proto3" json:"index18,omitempty"`
	Index19              *SQLIndex       `protobuf:"bytes,19,opt,name=index19,proto3" json:"index19,omitempty"`
	Index20              *SQLIndex       `protobuf:"bytes,20,opt,name=index20,proto3" json:"index20,omitempty"`
	Name                 string          `protobuf:"bytes,21,opt,name=name,proto3" json:"name,omitempty"`
	BelongsTo            *SQLAssociation `protobuf:"bytes,22,opt,name=belongs_to,json=belongsTo,proto3" json:"belongs_to,omitempty"`
	BelongsTo2           *SQLAssociation `protobuf:"bytes,23,opt,name=belongs_to2,json=belongsTo2,proto3" json:"belongs_to2,omitempty"`
	BelongsTo3           *SQLAssociation `protobuf:"bytes,24,opt,name=belongs_to3,json=belongsTo3,proto3" json:"belongs_to3,omitempty"`
	BelongsTo4           *SQLAssociation `protobuf:"bytes,25,opt,name=belongs_to4,json=belongsTo4,proto3" json:"belongs_to4,omitempty"`
	BelongsTo5           *SQLAssociation `protobuf:"bytes,26,opt,name=belongs_to5,json=belongsTo5,proto3" json:"belongs_to5,omitempty"`
	BelongsTo6           *SQLAssociation `protobuf:"bytes,27,opt,name=belongs_to6,json=belongsTo6,proto3" json:"belongs_to6,omitempty"`
	BelongsTo7           *SQLAssociation `protobuf:"bytes,28,opt,name=belongs_to7,json=belongsTo7,proto3" json:"belongs_to7,omitempty"`
	BelongsTo8           *SQLAssociation `protobuf:"bytes,29,opt,name=belongs_to8,json=belongsTo8,proto3" json:"belongs_to8,omitempty"`
	BelongsTo9           *SQLAssociation `protobuf:"bytes,30,opt,name=belongs_to9,json=belongsTo9,proto3" json:"belongs_to9,omitempty"`
	BelongsTo10          *SQLAssociation `protobuf:"bytes,31,opt,name=belongs_to10,json=belongsTo10,proto3" json:"belongs_to10,omitempty"`
	HasOne               *SQLAssociation `protobuf:"bytes,40,opt,name=has_one,json=hasOne,proto3" json:"has_one,omitempty"`
	HasOne2              *SQLAssociation `protobuf:"bytes,41,opt,name=has_one2,json=hasOne2,proto3" json:"has_one2,omitempty"`
	HasOne3              *SQLAssociation `protobuf:"bytes,42,opt,name=has_one3,json=hasOne3,proto3" json:"has_one3,omitempty"`
	HasOne4              *SQLAssociation `protobuf:"bytes,43,opt,name=has_one4,json=hasOne4,proto3" json:"has_one4,omitempty"`
	HasOne5              *SQLAssociation `protobuf:"bytes,44,opt,name=has_one5,json=hasOne5,proto3" json:"has_one5,omitempty"`
	HasOne6              *SQLAssociation `protobuf:"bytes,45,opt,name=has_one6,json=hasOne6,proto3" json:"has_one6,omitempty"`
	HasOne7              *SQLAssociation `protobuf:"bytes,46,opt,name=has_one7,json=hasOne7,proto3" json:"has_one7,omitempty"`
	HasOne8              *SQLAssociation `protobuf:"bytes,47,opt,name=has_one8,json=hasOne8,proto3" json:"has_one8,omitempty"`
	HasOne9              *SQLAssociation `protobuf:"bytes,48,opt,name=has_one9,json=hasOne9,proto3" json:"has_one9,omitempty"`
	HasOne10             *SQLAssociation `protobuf:"bytes,49,opt,name=has_one10,json=hasOne10,proto3" json:"has_one10,omitempty"`
	HasMany              *SQLAssociation `protobuf:"bytes,60,opt,name=has_many,json=hasMany,proto3" json:"has_many,omitempty"`
	HasMany2             *SQLAssociation `protobuf:"bytes,61,opt,name=has_many2,json=hasMany2,proto3" json:"has_many2,omitempty"`
	HasMany3             *SQLAssociation `protobuf:"bytes,62,opt,name=has_many3,json=hasMany3,proto3" json:"has_many3,omitempty"`
	HasMany4             *SQLAssociation `protobuf:"bytes,63,opt,name=has_many4,json=hasMany4,proto3" json:"has_many4,omitempty"`
	HasMany5             *SQLAssociation `protobuf:"bytes,64,opt,name=has_many5,json=hasMany5,proto3" json:"has_many5,omitempty"`
	HasMany6             *SQLAssociation `protobuf:"bytes,65,opt,name=has_many6,json=hasMany6,proto3" json:"has_many6,omitempty"`
	HasMany7             *SQLAssociation `protobuf:"bytes,66,opt,name=has_many7,json=hasMany7,proto3" json:"has_many7,omitempty"`
	HasMany8             *SQLAssociation `protobuf:"bytes,67,opt,name=has_many8,json=hasMany8,proto3" json:"has_many8,omitempty"`
	HasMany9             *SQLAssociation `protobuf:"bytes,68,opt,name=has_many9,json=hasMany9,proto3" json:"has_many9,omitempty"`
	HasMany10            *SQLAssociation `protobuf:"bytes,69,opt,name=has_many10,json=hasMany10,proto3" json:"has_many10,omitempty"`
	Nogenerate           bool            `protobuf:"varint,80,opt,name=nogenerate,proto3" json:"nogenerate,omitempty"`
	GqlAddType           *GraphQLType    `protobuf:"bytes,101,opt,name=gql_add_type,json=gqlAddType,proto3" json:"gql_add_type,omitempty"`
	GqlAddType1          *GraphQLType    `protobuf:"bytes,102,opt,name=gql_add_type1,json=gqlAddType1,proto3" json:"gql_add_type1,omitempty"`
	GqlAddType2          *GraphQLType    `protobuf:"bytes,103,opt,name=gql_add_type2,json=gqlAddType2,proto3" json:"gql_add_type2,omitempty"`
	GqlAddType3          *GraphQLType    `protobuf:"bytes,104,opt,name=gql_add_type3,json=gqlAddType3,proto3" json:"gql_add_type3,omitempty"`
	GqlAddType4          *GraphQLType    `protobuf:"bytes,105,opt,name=gql_add_type4,json=gqlAddType4,proto3" json:"gql_add_type4,omitempty"`
	GqlAddType5          *GraphQLType    `protobuf:"bytes,106,opt,name=gql_add_type5,json=gqlAddType5,proto3" json:"gql_add_type5,omitempty"`
	GqlAddType6          *GraphQLType    `protobuf:"bytes,107,opt,name=gql_add_type6,json=gqlAddType6,proto3" json:"gql_add_type6,omitempty"`
	GqlAddType7          *GraphQLType    `protobuf:"bytes,108,opt,name=gql_add_type7,json=gqlAddType7,proto3" json:"gql_add_type7,omitempty"`
	GqlAddType8          *GraphQLType    `protobuf:"bytes,109,opt,name=gql_add_type8,json=gqlAddType8,proto3" json:"gql_add_type8,omitempty"`
	GqlAddType9          *GraphQLType    `protobuf:"bytes,100,opt,name=gql_add_type9,json=gqlAddType9,proto3" json:"gql_add_type9,omitempty"`
	GqlUnion             *GraphQLUnion   `protobuf:"bytes,111,opt,name=gql_union,json=gqlUnion,proto3" json:"gql_union,omitempty"`
	GqlUnion2            *GraphQLUnion   `protobuf:"bytes,112,opt,name=gql_union2,json=gqlUnion2,proto3" json:"gql_union2,omitempty"`
	GqlUnion3            *GraphQLUnion   `protobuf:"bytes,113,opt,name=gql_union3,json=gqlUnion3,proto3" json:"gql_union3,omitempty"`
	GqlUnion4            *GraphQLUnion   `protobuf:"bytes,114,opt,name=gql_union4,json=gqlUnion4,proto3" json:"gql_union4,omitempty"`
	GqlUnion5            *GraphQLUnion   `protobuf:"bytes,115,opt,name=gql_union5,json=gqlUnion5,proto3" json:"gql_union5,omitempty"`
	GqlUnion6            *GraphQLUnion   `protobuf:"bytes,116,opt,name=gql_union6,json=gqlUnion6,proto3" json:"gql_union6,omitempty"`
	GqlUnion7            *GraphQLUnion   `protobuf:"bytes,117,opt,name=gql_union7,json=gqlUnion7,proto3" json:"gql_union7,omitempty"`
	GqlUnion8            *GraphQLUnion   `protobuf:"bytes,118,opt,name=gql_union8,json=gqlUnion8,proto3" json:"gql_union8,omitempty"`
	GqlUnion9            *GraphQLUnion   `protobuf:"bytes,119,opt,name=gql_union9,json=gqlUnion9,proto3" json:"gql_union9,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SQLMessageOptions) Reset()         { *m = SQLMessageOptions{} }
func (m *SQLMessageOptions) String() string { return proto.CompactTextString(m) }
func (*SQLMessageOptions) ProtoMessage()    {}
func (*SQLMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_75c6b13947912f81, []int{5}
}
func (m *SQLMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SQLMessageOptions.Unmarshal(m, b)
}
func (m *SQLMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SQLMessageOptions.Marshal(b, m, deterministic)
}
func (dst *SQLMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQLMessageOptions.Merge(dst, src)
}
func (m *SQLMessageOptions) XXX_Size() int {
	return xxx_messageInfo_SQLMessageOptions.Size(m)
}
func (m *SQLMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SQLMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SQLMessageOptions proto.InternalMessageInfo

func (m *SQLMessageOptions) GetIndex() *SQLIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex2() *SQLIndex {
	if m != nil {
		return m.Index2
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex3() *SQLIndex {
	if m != nil {
		return m.Index3
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex4() *SQLIndex {
	if m != nil {
		return m.Index4
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex5() *SQLIndex {
	if m != nil {
		return m.Index5
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex6() *SQLIndex {
	if m != nil {
		return m.Index6
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex7() *SQLIndex {
	if m != nil {
		return m.Index7
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex8() *SQLIndex {
	if m != nil {
		return m.Index8
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex9() *SQLIndex {
	if m != nil {
		return m.Index9
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex10() *SQLIndex {
	if m != nil {
		return m.Index10
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex11() *SQLIndex {
	if m != nil {
		return m.Index11
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex12() *SQLIndex {
	if m != nil {
		return m.Index12
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex13() *SQLIndex {
	if m != nil {
		return m.Index13
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex14() *SQLIndex {
	if m != nil {
		return m.Index14
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex15() *SQLIndex {
	if m != nil {
		return m.Index15
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex16() *SQLIndex {
	if m != nil {
		return m.Index16
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex17() *SQLIndex {
	if m != nil {
		return m.Index17
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex18() *SQLIndex {
	if m != nil {
		return m.Index18
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex19() *SQLIndex {
	if m != nil {
		return m.Index19
	}
	return nil
}

func (m *SQLMessageOptions) GetIndex20() *SQLIndex {
	if m != nil {
		return m.Index20
	}
	return nil
}

func (m *SQLMessageOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SQLMessageOptions) GetBelongsTo() *SQLAssociation {
	if m != nil {
		return m.BelongsTo
	}
	return nil
}

func (m *SQLMessageOptions) GetBelongsTo2() *SQLAssociation {
	if m != nil {
		return m.BelongsTo2
	}
	return nil
}

func (m *SQLMessageOptions) GetBelongsTo3() *SQLAssociation {
	if m != nil {
		return m.BelongsTo3
	}
	return nil
}

func (m *SQLMessageOptions) GetBelongsTo4() *SQLAssociation {
	if m != nil {
		return m.BelongsTo4
	}
	return nil
}

func (m *SQLMessageOptions) GetBelongsTo5() *SQLAssociation {
	if m != nil {
		return m.BelongsTo5
	}
	return nil
}

func (m *SQLMessageOptions) GetBelongsTo6() *SQLAssociation {
	if m != nil {
		return m.BelongsTo6
	}
	return nil
}

func (m *SQLMessageOptions) GetBelongsTo7() *SQLAssociation {
	if m != nil {
		return m.BelongsTo7
	}
	return nil
}

func (m *SQLMessageOptions) GetBelongsTo8() *SQLAssociation {
	if m != nil {
		return m.BelongsTo8
	}
	return nil
}

func (m *SQLMessageOptions) GetBelongsTo9() *SQLAssociation {
	if m != nil {
		return m.BelongsTo9
	}
	return nil
}

func (m *SQLMessageOptions) GetBelongsTo10() *SQLAssociation {
	if m != nil {
		return m.BelongsTo10
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne() *SQLAssociation {
	if m != nil {
		return m.HasOne
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne2() *SQLAssociation {
	if m != nil {
		return m.HasOne2
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne3() *SQLAssociation {
	if m != nil {
		return m.HasOne3
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne4() *SQLAssociation {
	if m != nil {
		return m.HasOne4
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne5() *SQLAssociation {
	if m != nil {
		return m.HasOne5
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne6() *SQLAssociation {
	if m != nil {
		return m.HasOne6
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne7() *SQLAssociation {
	if m != nil {
		return m.HasOne7
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne8() *SQLAssociation {
	if m != nil {
		return m.HasOne8
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne9() *SQLAssociation {
	if m != nil {
		return m.HasOne9
	}
	return nil
}

func (m *SQLMessageOptions) GetHasOne10() *SQLAssociation {
	if m != nil {
		return m.HasOne10
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany() *SQLAssociation {
	if m != nil {
		return m.HasMany
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany2() *SQLAssociation {
	if m != nil {
		return m.HasMany2
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany3() *SQLAssociation {
	if m != nil {
		return m.HasMany3
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany4() *SQLAssociation {
	if m != nil {
		return m.HasMany4
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany5() *SQLAssociation {
	if m != nil {
		return m.HasMany5
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany6() *SQLAssociation {
	if m != nil {
		return m.HasMany6
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany7() *SQLAssociation {
	if m != nil {
		return m.HasMany7
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany8() *SQLAssociation {
	if m != nil {
		return m.HasMany8
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany9() *SQLAssociation {
	if m != nil {
		return m.HasMany9
	}
	return nil
}

func (m *SQLMessageOptions) GetHasMany10() *SQLAssociation {
	if m != nil {
		return m.HasMany10
	}
	return nil
}

func (m *SQLMessageOptions) GetNogenerate() bool {
	if m != nil {
		return m.Nogenerate
	}
	return false
}

func (m *SQLMessageOptions) GetGqlAddType() *GraphQLType {
	if m != nil {
		return m.GqlAddType
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlAddType1() *GraphQLType {
	if m != nil {
		return m.GqlAddType1
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlAddType2() *GraphQLType {
	if m != nil {
		return m.GqlAddType2
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlAddType3() *GraphQLType {
	if m != nil {
		return m.GqlAddType3
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlAddType4() *GraphQLType {
	if m != nil {
		return m.GqlAddType4
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlAddType5() *GraphQLType {
	if m != nil {
		return m.GqlAddType5
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlAddType6() *GraphQLType {
	if m != nil {
		return m.GqlAddType6
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlAddType7() *GraphQLType {
	if m != nil {
		return m.GqlAddType7
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlAddType8() *GraphQLType {
	if m != nil {
		return m.GqlAddType8
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlAddType9() *GraphQLType {
	if m != nil {
		return m.GqlAddType9
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlUnion() *GraphQLUnion {
	if m != nil {
		return m.GqlUnion
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlUnion2() *GraphQLUnion {
	if m != nil {
		return m.GqlUnion2
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlUnion3() *GraphQLUnion {
	if m != nil {
		return m.GqlUnion3
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlUnion4() *GraphQLUnion {
	if m != nil {
		return m.GqlUnion4
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlUnion5() *GraphQLUnion {
	if m != nil {
		return m.GqlUnion5
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlUnion6() *GraphQLUnion {
	if m != nil {
		return m.GqlUnion6
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlUnion7() *GraphQLUnion {
	if m != nil {
		return m.GqlUnion7
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlUnion8() *GraphQLUnion {
	if m != nil {
		return m.GqlUnion8
	}
	return nil
}

func (m *SQLMessageOptions) GetGqlUnion9() *GraphQLUnion {
	if m != nil {
		return m.GqlUnion9
	}
	return nil
}

type SQLFileOptions struct {
	LowercaseEnums       bool     `protobuf:"varint,1,opt,name=lowercaseEnums,proto3" json:"lowercaseEnums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SQLFileOptions) Reset()         { *m = SQLFileOptions{} }
func (m *SQLFileOptions) String() string { return proto.CompactTextString(m) }
func (*SQLFileOptions) ProtoMessage()    {}
func (*SQLFileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_75c6b13947912f81, []int{6}
}
func (m *SQLFileOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SQLFileOptions.Unmarshal(m, b)
}
func (m *SQLFileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SQLFileOptions.Marshal(b, m, deterministic)
}
func (dst *SQLFileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQLFileOptions.Merge(dst, src)
}
func (m *SQLFileOptions) XXX_Size() int {
	return xxx_messageInfo_SQLFileOptions.Size(m)
}
func (m *SQLFileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SQLFileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SQLFileOptions proto.InternalMessageInfo

func (m *SQLFileOptions) GetLowercaseEnums() bool {
	if m != nil {
		return m.LowercaseEnums
	}
	return false
}

type SQLEnumValueOptions struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SQLEnumValueOptions) Reset()         { *m = SQLEnumValueOptions{} }
func (m *SQLEnumValueOptions) String() string { return proto.CompactTextString(m) }
func (*SQLEnumValueOptions) ProtoMessage()    {}
func (*SQLEnumValueOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_75c6b13947912f81, []int{7}
}
func (m *SQLEnumValueOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SQLEnumValueOptions.Unmarshal(m, b)
}
func (m *SQLEnumValueOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SQLEnumValueOptions.Marshal(b, m, deterministic)
}
func (dst *SQLEnumValueOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQLEnumValueOptions.Merge(dst, src)
}
func (m *SQLEnumValueOptions) XXX_Size() int {
	return xxx_messageInfo_SQLEnumValueOptions.Size(m)
}
func (m *SQLEnumValueOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SQLEnumValueOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SQLEnumValueOptions proto.InternalMessageInfo

func (m *SQLEnumValueOptions) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

var E_File = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*SQLFileOptions)(nil),
	Field:         1034,
	Name:          "proto.file",
	Tag:           "bytes,1034,opt,name=file",
	Filename:      "annotations.proto",
}

var E_Column = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*SQLFieldOptions)(nil),
	Field:         1034,
	Name:          "proto.column",
	Tag:           "bytes,1034,opt,name=column",
	Filename:      "annotations.proto",
}

var E_Table = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*SQLMessageOptions)(nil),
	Field:         1034,
	Name:          "proto.table",
	Tag:           "bytes,1034,opt,name=table",
	Filename:      "annotations.proto",
}

var E_Enumval = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*SQLEnumValueOptions)(nil),
	Field:         1034,
	Name:          "proto.enumval",
	Tag:           "bytes,1034,opt,name=enumval",
	Filename:      "annotations.proto",
}

func init() {
	proto.RegisterType((*SQLIndex)(nil), "proto.SQLIndex")
	proto.RegisterType((*SQLAssociation)(nil), "proto.SQLAssociation")
	proto.RegisterType((*SQLFieldOptions)(nil), "proto.SQLFieldOptions")
	proto.RegisterType((*GraphQLType)(nil), "proto.GraphQLType")
	proto.RegisterType((*GraphQLUnion)(nil), "proto.GraphQLUnion")
	proto.RegisterType((*SQLMessageOptions)(nil), "proto.SQLMessageOptions")
	proto.RegisterType((*SQLFileOptions)(nil), "proto.SQLFileOptions")
	proto.RegisterType((*SQLEnumValueOptions)(nil), "proto.SQLEnumValueOptions")
	proto.RegisterExtension(E_File)
	proto.RegisterExtension(E_Column)
	proto.RegisterExtension(E_Table)
	proto.RegisterExtension(E_Enumval)
}

func init() { proto.RegisterFile("annotations.proto", fileDescriptor_annotations_75c6b13947912f81) }

var fileDescriptor_annotations_75c6b13947912f81 = []byte{
	// 1171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd8, 0xf9, 0x72, 0xdb, 0x44,
	0x1c, 0x07, 0xf0, 0x89, 0x49, 0x7c, 0xac, 0xd3, 0x84, 0x6c, 0xd2, 0xf0, 0x23, 0x4d, 0x0f, 0x3c,
	0x03, 0xb4, 0x14, 0x1c, 0xdd, 0x47, 0x86, 0x2b, 0x40, 0xcb, 0x31, 0x2e, 0xad, 0x9d, 0xc2, 0x30,
	0xfc, 0x41, 0x46, 0x89, 0x64, 0x47, 0x58, 0x96, 0x6c, 0x4b, 0x4a, 0xc9, 0x2b, 0xf0, 0x4a, 0x3c,
	0x09, 0x6f, 0xd3, 0xd1, 0xea, 0xd8, 0x95, 0x12, 0xab, 0xfb, 0x57, 0xb4, 0xd2, 0xf7, 0xf3, 0xdb,
	0x5d, 0xaf, 0xa2, 0xd1, 0x0a, 0xed, 0x58, 0xbe, 0x1f, 0x44, 0x56, 0xe4, 0x06, 0x7e, 0xd8, 0x9f,
	0x2f, 0x83, 0x28, 0xc0, 0x1b, 0xe4, 0xcf, 0xc1, 0xa3, 0x49, 0x10, 0x4c, 0x3c, 0xe7, 0x88, 0xb4,
	0xce, 0xe3, 0xf1, 0x91, 0xed, 0x84, 0x17, 0x4b, 0x77, 0x1e, 0x05, 0xcb, 0x34, 0xd8, 0xfb, 0x05,
	0xb5, 0x4f, 0x87, 0x83, 0x9f, 0x7d, 0xdb, 0xf9, 0x07, 0x63, 0xb4, 0xee, 0x5b, 0x33, 0x07, 0xd6,
	0x1e, 0xad, 0x3d, 0xee, 0x8c, 0xc8, 0x31, 0xde, 0x47, 0xcd, 0xb1, 0xeb, 0x78, 0x76, 0x08, 0x0d,
	0x72, 0x36, 0x6b, 0x25, 0xd9, 0xe8, 0x7a, 0xee, 0xc0, 0x7b, 0x69, 0x36, 0x39, 0xee, 0xfd, 0x89,
	0xb6, 0x4e, 0x87, 0x83, 0x93, 0x30, 0x0c, 0x2e, 0x5c, 0x32, 0x1a, 0xbc, 0x87, 0x36, 0x22, 0xeb,
	0xdc, 0xcb, 0x4b, 0xa6, 0x0d, 0xbc, 0x85, 0x1a, 0xf3, 0x69, 0x56, 0xaf, 0x31, 0x9f, 0x26, 0xed,
	0xf1, 0x34, 0xab, 0xd4, 0x18, 0x4f, 0x8b, 0x71, 0xac, 0xd3, 0x71, 0xf4, 0xfe, 0x5f, 0x43, 0xdb,
	0xa7, 0xc3, 0xc1, 0xf3, 0xa4, 0xf7, 0x97, 0x73, 0x32, 0xd5, 0x64, 0x6c, 0xb1, 0xef, 0x2e, 0xe2,
	0xb4, 0x7c, 0x7b, 0x94, 0xb5, 0x92, 0x5e, 0xdd, 0x64, 0x42, 0xa4, 0x8b, 0xf6, 0x28, 0x6d, 0xe0,
	0x43, 0xd4, 0x21, 0x07, 0xcc, 0xb0, 0xe9, 0x89, 0x62, 0x3e, 0xeb, 0x74, 0x3e, 0xf8, 0x01, 0x42,
	0xf3, 0xa5, 0x3b, 0xb3, 0x96, 0xd7, 0x53, 0xe7, 0x1a, 0x36, 0x48, 0x31, 0xe6, 0x0c, 0x06, 0xd4,
	0xf2, 0x83, 0xc8, 0x8f, 0x3d, 0x0f, 0x9a, 0xe4, 0x62, 0xde, 0x2c, 0x66, 0xd0, 0x62, 0x7e, 0x49,
	0x40, 0x2d, 0xdb, 0x19, 0x5b, 0xb1, 0x17, 0x41, 0x9b, 0x9c, 0xce, 0x9b, 0xbd, 0x05, 0xea, 0xfe,
	0xb8, 0xb4, 0xe6, 0x97, 0xc3, 0xc1, 0xeb, 0x6c, 0x28, 0x37, 0x96, 0x21, 0x1f, 0x5e, 0x83, 0x19,
	0xde, 0x01, 0x6a, 0x4f, 0x1c, 0xdf, 0x59, 0x5a, 0x51, 0x3a, 0x9f, 0xf6, 0xa8, 0x68, 0x27, 0x43,
	0xb7, 0x9d, 0xb1, 0xeb, 0xbb, 0xc9, 0x2f, 0x95, 0x4d, 0x8a, 0x39, 0xd3, 0xfb, 0x0b, 0x6d, 0x66,
	0x5d, 0xfe, 0xe6, 0x27, 0x0b, 0x75, 0x5b, 0x9f, 0x5b, 0xa8, 0xe1, 0xda, 0xf9, 0x32, 0xb9, 0xf6,
	0x6d, 0x4b, 0x9e, 0x2c, 0x01, 0x59, 0xd3, 0x30, 0xeb, 0x23, 0x6b, 0xf5, 0xfe, 0xbb, 0x87, 0x76,
	0x4e, 0x87, 0x83, 0x17, 0x4e, 0x18, 0x5a, 0x13, 0x27, 0x5f, 0xb0, 0x8f, 0xf3, 0x85, 0x49, 0xba,
	0xe9, 0x4a, 0xdb, 0xe9, 0x3d, 0xd8, 0xcf, 0x6f, 0xc0, 0x7c, 0xa5, 0x3e, 0x45, 0x4d, 0x72, 0x20,
	0x91, 0xce, 0x6f, 0xc9, 0x65, 0x97, 0x8b, 0xa0, 0x4c, 0xc6, 0xb4, 0x32, 0x28, 0x17, 0x41, 0x85,
	0x0c, 0x73, 0x65, 0x50, 0x29, 0x82, 0x2a, 0x59, 0xee, 0x95, 0x41, 0xb5, 0x08, 0x6a, 0x64, 0xe9,
	0x57, 0x06, 0xb5, 0x22, 0xa8, 0x93, 0x9b, 0x61, 0x65, 0x50, 0x2f, 0x82, 0x06, 0xb9, 0x3d, 0x56,
	0x06, 0x8d, 0x22, 0x68, 0x42, 0xa7, 0x2e, 0x68, 0xe2, 0x27, 0xa8, 0x45, 0x8e, 0x44, 0x01, 0xd0,
	0xed, 0xc9, 0xfc, 0x3a, 0x8d, 0x8a, 0xd0, 0xad, 0x8d, 0x8a, 0x34, 0x2a, 0xc1, 0x66, 0x6d, 0x54,
	0xa2, 0x51, 0x19, 0xee, 0xd4, 0x46, 0x65, 0x1a, 0x55, 0x60, 0xab, 0x36, 0xaa, 0xd0, 0xa8, 0x0a,
	0xdb, 0xb5, 0x51, 0x95, 0x46, 0x35, 0x78, 0xbf, 0x36, 0xaa, 0xd1, 0xa8, 0x0e, 0x3b, 0xb5, 0x51,
	0x9d, 0x46, 0x0d, 0xc0, 0xb5, 0x51, 0x83, 0x46, 0x4d, 0xd8, 0xad, 0x8d, 0xd2, 0xd5, 0x92, 0x04,
	0xd8, 0xab, 0x8b, 0x4a, 0x42, 0xf1, 0xdf, 0x7a, 0x97, 0xf9, 0x6f, 0x55, 0x10, 0x3a, 0x77, 0xbc,
	0xc0, 0x9f, 0x84, 0x67, 0x51, 0x00, 0xfb, 0xa4, 0xc2, 0x5d, 0x5a, 0x81, 0x79, 0x2a, 0x8f, 0x3a,
	0x59, 0xf0, 0x75, 0x80, 0x35, 0xd4, 0xa5, 0x4a, 0x82, 0x0f, 0xea, 0x18, 0x2a, 0x98, 0x54, 0x76,
	0x32, 0x00, 0x9f, 0x93, 0xcb, 0x4e, 0x81, 0x0f, 0xf9, 0x9c, 0x52, 0x76, 0x2a, 0x1c, 0xf0, 0x39,
	0xb5, 0xec, 0x34, 0xb8, 0xc7, 0xe7, 0xb4, 0xb2, 0xd3, 0xe1, 0x90, 0xcf, 0xe9, 0x65, 0x67, 0xc0,
	0x7d, 0x3e, 0x67, 0x94, 0x9d, 0x09, 0x0f, 0xf8, 0x9c, 0x89, 0x0d, 0xb4, 0x49, 0x9d, 0x28, 0xc0,
	0xc3, 0x3a, 0xd8, 0x2d, 0xa0, 0x28, 0xe0, 0x3e, 0x6a, 0x5d, 0x5a, 0xe1, 0x59, 0xe0, 0x3b, 0xf0,
	0xb8, 0x0e, 0x35, 0x2f, 0xad, 0xf0, 0xa5, 0xef, 0x60, 0x01, 0xb5, 0xb3, 0xbc, 0x04, 0x4f, 0xea,
	0x40, 0x2b, 0x05, 0x12, 0x23, 0x64, 0xf8, 0x8c, 0x43, 0xc8, 0x8c, 0x50, 0xe0, 0x29, 0x87, 0x50,
	0x18, 0xa1, 0xc2, 0xe7, 0x1c, 0x42, 0x65, 0x84, 0x06, 0x5f, 0x70, 0x08, 0x8d, 0x11, 0x3a, 0xf4,
	0x39, 0x84, 0xce, 0x08, 0x03, 0x8e, 0x38, 0x84, 0xc1, 0x08, 0x13, 0x04, 0x0e, 0x61, 0x62, 0x09,
	0x75, 0x32, 0x21, 0x0a, 0x20, 0xd6, 0x91, 0x76, 0x4a, 0x44, 0x21, 0xef, 0x65, 0x66, 0xf9, 0xd7,
	0xf0, 0xe5, 0xbb, 0x7a, 0x79, 0x61, 0xf9, 0xd7, 0x79, 0x2f, 0x89, 0x90, 0xe0, 0xab, 0x77, 0xf5,
	0x92, 0x10, 0x89, 0x35, 0x32, 0x7c, 0xcd, 0x63, 0x64, 0xd6, 0x28, 0xf0, 0x0d, 0x8f, 0x51, 0x58,
	0xa3, 0xc2, 0xb7, 0x3c, 0x46, 0x65, 0x8d, 0x06, 0x27, 0x3c, 0x46, 0x63, 0x8d, 0x0e, 0xdf, 0xf1,
	0x18, 0x9d, 0x35, 0x06, 0x7c, 0xcf, 0x63, 0x0c, 0xd6, 0x98, 0xf0, 0x03, 0x8f, 0x31, 0x93, 0xa7,
	0x7e, 0x6e, 0x44, 0x01, 0x9e, 0xd5, 0x3e, 0xf5, 0x33, 0x24, 0x0a, 0xc9, 0xdb, 0xa1, 0x1f, 0x14,
	0xef, 0x8e, 0xaf, 0xd2, 0x17, 0x5b, 0x7a, 0x06, 0x2b, 0x68, 0x73, 0xb2, 0xf0, 0xce, 0x2c, 0xdb,
	0x3e, 0x23, 0x6f, 0x7c, 0x0e, 0xa9, 0x8b, 0xb3, 0xba, 0xcc, 0xbb, 0xea, 0x08, 0x4d, 0x16, 0xde,
	0x89, 0x6d, 0x93, 0xf7, 0x56, 0x0d, 0xdd, 0x61, 0x95, 0x08, 0xe3, 0x95, 0xac, 0x4b, 0x99, 0x58,
	0x75, 0x12, 0x4c, 0x78, 0x9c, 0x54, 0x75, 0x32, 0x5c, 0xf2, 0x38, 0xb9, 0xea, 0x14, 0x70, 0x79,
	0x9c, 0x52, 0x75, 0x2a, 0xfc, 0xcd, 0xe3, 0xd4, 0xaa, 0xd3, 0x60, 0xca, 0xe3, 0xb4, 0xaa, 0xd3,
	0xc1, 0xe3, 0x71, 0x7a, 0xd5, 0x19, 0x30, 0xe3, 0x71, 0x46, 0xd5, 0x99, 0x60, 0xf3, 0x38, 0x13,
	0x0b, 0xa8, 0x93, 0xb8, 0x38, 0xd9, 0x48, 0x40, 0x40, 0xcc, 0x6e, 0xd9, 0x90, 0x3d, 0xc6, 0xa8,
	0x3d, 0x59, 0x78, 0xe9, 0x6e, 0x43, 0x42, 0xa8, 0x10, 0x12, 0xcc, 0x57, 0x93, 0x4e, 0x4e, 0xa4,
	0x92, 0x91, 0x61, 0xc1, 0x61, 0xe4, 0x92, 0x51, 0x60, 0xc9, 0x61, 0x94, 0x92, 0x51, 0x21, 0xe4,
	0x30, 0x6a, 0xc9, 0x68, 0x10, 0x71, 0x18, 0xad, 0x64, 0x74, 0x88, 0x39, 0x8c, 0x5e, 0x32, 0x06,
	0x5c, 0x71, 0x18, 0xa3, 0x64, 0x4c, 0x78, 0xc3, 0x61, 0xcc, 0x9e, 0x41, 0x36, 0xf2, 0xcf, 0x5d,
	0xaf, 0xd8, 0xb9, 0x7d, 0x82, 0xb6, 0xbc, 0xe0, 0x8d, 0xb3, 0xbc, 0xb0, 0x42, 0xe7, 0x99, 0x1f,
	0xcf, 0xc2, 0x6c, 0xcb, 0x5d, 0x39, 0xdb, 0x7b, 0x8a, 0x76, 0x4f, 0x87, 0x83, 0xe4, 0xf8, 0x77,
	0xcb, 0x8b, 0x0b, 0xbe, 0x87, 0x36, 0xae, 0x92, 0x76, 0xfe, 0x1d, 0x80, 0x34, 0x8e, 0x7f, 0x42,
	0xeb, 0x63, 0xd7, 0x73, 0xf0, 0x61, 0x3f, 0xfd, 0x4c, 0xd1, 0xcf, 0x3f, 0x53, 0xf4, 0x99, 0xae,
	0xe1, 0xdf, 0x76, 0xf5, 0xa9, 0xc6, 0x5c, 0x1d, 0x91, 0x0a, 0xc7, 0xbf, 0xa2, 0xe6, 0x45, 0xe0,
	0xc5, 0x33, 0x1f, 0xdf, 0xbf, 0xa5, 0x16, 0xfd, 0x64, 0x90, 0x17, 0xdb, 0x67, 0x8b, 0xd1, 0xcb,
	0xa3, 0xac, 0xca, 0xf1, 0xab, 0xec, 0xbb, 0x05, 0x7e, 0x78, 0xa3, 0x5c, 0x79, 0x4b, 0x9b, 0x17,
	0x04, 0x5a, 0xb0, 0x1c, 0xc8, 0xbe, 0x79, 0x1c, 0xff, 0x81, 0x5a, 0x8e, 0x1f, 0xcf, 0xae, 0x2c,
	0x0f, 0x7f, 0x74, 0xa3, 0x66, 0xf5, 0xf7, 0xca, 0xab, 0x1e, 0xd0, 0xaa, 0xd5, 0xc8, 0x28, 0x2f,
	0x77, 0xde, 0x24, 0x19, 0xf9, 0x6d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0x96, 0xd6, 0x1f, 0x06,
	0x12, 0x00, 0x00,
}
